### PR TITLE
Allow using openssl crate for cryptographic primitives

### PR DESCRIPTION
**Pull request by ueno**
This allows oo7 to selectively use the openssl crate instead of the
RustCrypto crates, when `openssl_crypto` feature is enabled.  The
motivation behind this is to make it FIPS 140 compliant by delegating
the cryptographic primitives implementation to the FIPS-certified
system library (i.e., libcrypto.so in OpenSSL).

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Thank you for your PR, although I think we should still have an optional feature for opting-out of OpenSSL instead of dropping the current code completely

**Comment by ueno** [comment]
Yes, I agree (pulling in openssl may also mean a license change to ASL-2.0). Let me add a build-time feature.

**Comment by ueno** [comment]
@bilelmoussaoui I think the CI should pass now; could you retrigger the workflow?

**Review by bilelmoussaoui — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
lgtm, thanks a lot!

**Pull request merged**
